### ISSUE TITLE
Error in the xamarin sample download link

### ISSUE THREAD

**Issue by kkarakk** [xamarin/mobile-samples#103]
### Sample

https://developer.xamarin.com/samples/mobile/BackgroundLocationDemo/BackgroundLocationDemo.zip

### Description

Duplicate ic_launcher.png files exist in the downloaded xamarin code solution but not in the github. sorry if this isn't the place but i don't know where to raise an issue with the documentation code downloads

**Comment by conceptdev** [comment]
The download matches the GitHub repo at https://github.com/xamarin/mobile-samples/tree/master/BackgroundLocationDemo/location.Android/Resources as far as I can see. **icon** and **ic_launcher** files exist in multiple resource folders because they are for different screen resolutions.

**Comment by kkarakk** [comment]
i have verified that it was actually a problem with my unzipping tool creating duplicates. why are the xamarin mobile samples created monolithically like this so i can't just download individual samples from github directly?

**Comment by conceptdev** [comment]
I'm glad you got it working.

While some customers prefer to download individual samples, others _like_ the opportunity to grab the entire set, so they can explore. Having a single samples repo (for each platform: Xamarin.Forms, iOS, Android) but with individual ZIPs available from our samples gallery serves both.
