### ISSUE TITLE
ALittleStory.txt does not contain a haiku

### ISSUE THREAD

**Issue by swkidd** [xamarin/mobile-samples#109]
### Sample

mobile-samples/EmbeddedResources/SharedLib/ALittleStory.txt

### Description

      mobile-samples/EmbeddedResources/SharedLib/ALittleStory.txt
      does not contain a haiku

### Expected Behavior

Expected a haiku

### Actual Behavior

This is not a haiku
(should be 5-7-5 syllables)

## Suggested Haiku
I like to eat soup
I did not used to like soup
but now I like soup

**Comment by conceptdev** [comment]
Thanks for your feedback and suggested fix!
