### ISSUE TITLE
Creating .fbx

### ISSUE THREAD

**Issue by Rombersoft** [xamarin/mobile-samples#111]
Hello developer. How you create .fbx model for this https://github.com/xamarin/mobile-samples/blob/master/ModelRenderingMG/Resources/Content.zip?raw=true ? What did you use tools?

**Comment by rolfbjarne** [comment]
@vchelaru It seems you're the author for the ModelRenderingMG (according to the [README](https://github.com/xamarin/mobile-samples/blob/master/ModelRenderingMG/README.md)): can you answer this question?

**Comment by vchelaru** [comment]
This fbx was downloaded from some CC0 source, I don't recall where

I believe any 3D modeling app will work. Blender is the most popular free option.
