### ISSUE TITLE
Question - Can we get street name or anything rather than just GPS coordinates?

### ISSUE THREAD

**Issue by Korporal** [xamarin/mobile-samples#115]
I don't know if this is the ideal place to ask such a question, if not please let me know where I can ask this and future tech questions.

I'm just looking into the feasibility of a new app and this is a new area for me. I'd like to know what components or libraries or services one must have in order to get a user's location as a street name or something rather than raw latitude/longitude coordinates.

I'm a _very_ experienced .Net developer but brand new to mobile and Xamarin. I'm hoping to use Visual Studio Enterprise 2019 to build this application, this is simply a question that's come up as I define the requirements for the app.

**Comment by conceptdev** [comment]
It's called reverse geocoding, and you can ready about it [here](https://docs.microsoft.com/xamarin/essentials/geocoding#using-reverse-geocoding). Results returned by reverse-geocoding can vary greatly by country and region.

In future, the best place to ask questions is one of the **Keep in touch with us** options near the bottom of this page - https://docs.microsoft.com/xamarin/ - especially the Forums.
