### ISSUE TITLE
Invalid file path

### ISSUE THREAD

**Issue by pytchoun** [xamarin/mobile-samples#119]
https://i.imgur.com/0OMbVJT.png

Hello

I just take the repo and i have a error when i build why ?

**Comment by rolfbjarne** [comment]
Please attach the full build log.

Logs can be found in the Build Output tab of the Errors pad in Visual Studio
To get full build logs, set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

**Comment by tuukkapuranen** [comment]
I ran into the same issue, and fixed this by removing the [line 77](https://github.com/xamarin/mobile-samples/blob/257f7fe81e70b412d6a6b42e97019ecc2c46ed40/BackgroundLocationDemo/location.Android/Location.Droid.csproj#L77) from the background location sample project file. It seems that the same resource is defined twice in the project:

```
<AndroidResource Include="Resources\drawable\ic_launcher.png" />
<AndroidResource Include="..\location.Android\Resources\drawable\ic_launcher.png" />
```

and at least in my environment, this causes the build to fail with "invalid file path" error.

[This issue](https://github.com/xamarin/xamarin-android/issues/5052) may be related.
