### ISSUE TITLE
Can't pick a date

### ISSUE THREAD

**Issue by stesvis** [xamarin/mobile-samples#15]
Hi,

using iOS 7 on iPhone I can't pick a date. When I scroll Month, Day, Year it won't stop where I stop.

If I scroll from January to May, for example, once I release my finger it scrolls on its own and doesn't pick the month I wanted.

What's wrong?

**Comment by bradumbaugh** [comment]
Apologies that this was never addressed. I'm going to close this – I took a quick look at the iOSStandardControls sample to see if I could reproduce the error, but I cannot. Thanks!
