### ISSUE TITLE
A few questions about the game CoinTime

### ISSUE THREAD

**Issue by jonathanzuniga** [xamarin/mobile-samples#33]
Hello!

Does the character from the game CoinTime have more moves besides jump?
Are you planning to make a guide or tutorial?

Keep up the great work! Thank you.

**Comment by conceptdev** [comment]
@jonathanzuniga yes, we are planning some guides explaining how we built CoinTime and in future perhaps some ways you can extend it.

There are no additional moves built for the character yet - but if you look at the game assets (using [Tiled app](http://www.mapeditor.org/)) you'll see there are some pre-drawn frames for a punch, a kick, and "shooting"... and also frames for the red enemy to get "squashed".

![cointime](https://cloud.githubusercontent.com/assets/199373/10706805/44ae9428-799f-11e5-849d-b96531d99a2b.png)
