### ISSUE TITLE
MWC.iOS: compilation exceptions

### ISSUE THREAD

**Issue by aberbenni** [xamarin/mobile-samples#5]
Building Solution: MWC.iOS (Debug|iPhoneSimulator)

Generazione: MWC.Core.MT (Debug|iPhoneSimulator)
Performing main compilation...
/Developer/MonoTouch/usr/bin/smcs /noconfig "/out:/
 mobile-samples/MWC/MWC.Core/bin/iPhoneSimulator/Debug/MWCCoreMT.dll" "/r:/Developer/MonoTouch/usr/lib/mono/2.1/System.dll" "/r:/Developer/MonoTouch/usr/lib/mono/2.1/System.Xml.dll" "/r:/Developer/MonoTouch/usr/lib/mono/2.1/System.Core.dll" "/r:/Developer/MonoTouch/usr/lib/mono/2.1/monotouch.dll" "/r:/Developer/MonoTouch/usr/lib/mono/2.1/System.Xml.Linq.dll" /nologo /warn:4 /debug:full /optimize- /codepage:utf8 "/define:DEBUG"  /t:library "/mobile-samples/MWC/MWC.Core/DL/MwcDatabase.cs" "/mobile-samples/MWC/MWC.Core/DL/SQLite.cs" "/mobile-samples/MWC/MWC.Core/BL/Session.cs" "/mobile-samples/MWC/MWC.Core/BL/Exhibitor.cs" "/mobile-samples/MWC/MWC.Core/BL/Speaker.cs" "/mobile-samples/MWC/MWC.Core/BL/Contracts/BusinessEntityBase.cs" "/mobile-samples/MWC/MWC.Core/DAL/DataManager.cs" "/mobile-samples/MWC/MWC.Core/BL/Managers/SessionManager.cs" "/mobile-samples/MWC/MWC.Core/BL/Managers/UpdateManager.cs" "/mobile-samples/MWC/MWC.Core/BL/Managers/SpeakerManager.cs" "/mobile-samples/MWC/MWC.Core/BL/Managers/ExhibitorManager.cs" "/mobile-samples/MWC/MWC.Core/BL/Managers/TwitterFeedManager.cs" "/mobile-samples/MWC/MWC.Core/SAL/MwcSiteParser.cs" "/mobile-samples/MWC/MWC.Core/BL/Managers/NewsManager.cs" "/mobile-samples/MWC/MWC.Core/BL/Contracts/IBusinessEntity.cs" "/mobile-samples/MWC/MWC.Core/SAL/Tweet.cs" "/mobile-samples/MWC/MWC.Core/SAL/RSSEntry.cs" "/mobile-samples/MWC/MWC.Core/SAL/XmlFeedParserBase.cs" "/mobile-samples/MWC/MWC.Core/SAL/TwitterParser.cs" "/mobile-samples/MWC/MWC.Core/SAL/RSSParser.cs" "/mobile-samples/MWC/MWC.Core/BL/Conference.cs" "/mobile-samples/MWC/MWC.Core/BL/Managers/FavoritesManager.cs" "/mobile-samples/MWC/MWC.Core/BL/Favorite.cs" "/mobile-samples/MWC/MWC.Core/BL/SessionTimeslot.cs" "/mobile-samples/MWC/MWC.Core/Constants.cs" "/mobile-samples/MWC/MWC.Core/BL/Managers/DaysManager.cs" "/mobile-samples/MWC/MWC.Core/BL/Managers/UpdateFinishedEventArgs.cs" "/mobile-samples/MWC/MWC.Core/BL/SessionSpeaker.cs" 
Compilation failed: 2 error(s), 0 warnings

/mobile-samples/MWC/MWC.Core/DL/MwcDatabase.cs(90,60): error CS1061: Type 'T' does not contain a definition for Id' and no extension method 'Id' of type 'T' could be found (are you missing a using directive or an assembly reference?)
/mobile-samples/MWC/MWC.Core/DL/MwcDatabase.cs(79,33): (Location of the symbol related to previous error)
/mobile-samples/MWC/MWC.Core/DL/MwcDatabase.cs(79,33): error CS0161: `MWC.DL.MwcDatabase.GetItem<T>(int)': not all code paths return a value

**Comment by bradumbaugh** [comment]
Closing this issue since this sample has been deprecated.
