### ISSUE TITLE
SharingCode doesn't share with Android

### ISSUE THREAD

**Issue by jadbox** [xamarin/mobile-samples#56]
It doesn't seem like the Android project ever actually calls to CalculateArea function in the shared project folder.

**Comment by conceptdev** [comment]
oops! You're right, it should probably be called in `MainActivity`, to match the use in [iOS](https://github.com/xamarin/mobile-samples/blob/master/SharingCode/NativeShared.iOS/NativeShared.iOSViewController.cs#L34).
Adding it now...
