### ISSUE TITLE
snow particles disappear when it showed for second time

### ISSUE THREAD

**Issue by ghost** [xamarin/mobile-samples#59]
I have 2 pages ,In first page when I click one of the item in listview,it should navigate to 2nd page and here in 2nd page snow particles are appeared.After that when I click back button,As usual it goes to first page and again when I click any of the listview items ,when it navigates to 2nd page ,snow particles disappear,It just show a black screen.

For detail codes,I am following this- https://github.com/codemillmatt/forms-particle Please help me..............

**Comment by conceptdev** [comment]
Unfortunately we cannot provide support for outside code, try opening an issue on the repo with the original source.
