### ISSUE TITLE
TaskyWin8.csproj loading not supported in Visual Studio 2017

### ISSUE THREAD

**Issue by dbaechtel** [xamarin/mobile-samples#60]
What do I need to do to build it with Visual Studio 2017 ?

Tasky.Win81\Tasky.Win81.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=BC8A1FFA-BEE3-4634-8014-F334798102B3

Tasky.WinPhone8\Tasky.WinPhone8.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=C089C8C0-30E0-4E22-80C0-CE093F111A43

**Comment by murkle** [comment]
https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects
Windows Store/Phone apps: Projects for Windows Store 8.1 and 8.0, and Windows Phone 8.1 and 8.0 are not supported in Visual Studio 2017. To maintain these apps, continue to use Visual Studio 2015. To maintain Windows Phone 7.x projects, use Visual Studio 2012.

**Comment by conceptdev** [comment]
@dbaechtel this sample requires an update - those project types are no longer supported (as you have discovered from the error messages). An updated version will be pushed to GitHub shortly - thanks for reporting this issue.

**Comment by conceptdev** [comment]
This repo was not being monitored as it should have been. We plan to do better in future.
