### ISSUE TITLE
WheatherApp not opening in solution

### ISSUE THREAD

**Issue by eqonto** [xamarin/mobile-samples#79]
Windows app project is not loading, I get following error. What can be wrong with csproj file?

I'm using latest VS2017 Community edition

Microsoft Visual Studio Community 2017 
Version 15.2 (26430.16) Release
VisualStudio.15.Release/15.2.0+26430.16
Microsoft .NET Framework
Version 4.7.02558
Visual Studio Tools for Universal Windows Apps   15.0.26430.06
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Xamarin   4.5.0.486 (fec6f88)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android SDK   7.3.1.2 (9dbc4c5)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   10.10.0.37 (ad35de4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

Log in browser:
WeatherApp\WeatherApp.WinPhone\WeatherApp.WinPhone.csproj: The application which this project type is based on was not foun
--

Pop up window:

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - WeatherApp.WinPhone, "D:\mobile-samples\Weather\WeatherApp\WeatherApp.WinPhone\WeatherApp.WinPhone.csproj"

No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - WeatherApp.Droid, "D:\mobile-samples\Weather\WeatherApp\WeatherApp.Droid\WeatherApp.Droid.csproj"
	 - WeatherApp.iOS, "D:\mobile-samples\Weather\WeatherApp\WeatherApp.iOS\WeatherApp.iOS.csproj"
	 - WeatherApp, "D:\mobile-samples\Weather\WeatherApp\WeatherApp\WeatherApp.csproj"
	 - WeatherApp, "D:\mobile-samples\Weather\WeatherApp.sln"

**Comment by conceptdev** [comment]
This sample may require an update (older style Windows projects are no longer supported). Thanks for letting us know, will push an update to GitHub soon.

**Comment by conceptdev** [comment]
The older Windows style projects were replaced with UWP in [this commit](https://github.com/xamarin/mobile-samples/commit/b971084ba94489dece0c2a80fe15561e7bfab96f#diff-1441df6b1c10f910ccdc400e40b5fce9). I hope that helps!
