### ISSUE TITLE
SQLite errors with WP7.1

### ISSUE THREAD

**Issue by jstawski** [xamarin/mobile-samples#8]
I'm trying to compile the MWC.WP7.sln using VS 2010 or 2012, but it doesn't compile because of SQLite. I get 

> Error 6   Argument 1 must be passed with the 'ref' keyword    ..\Visual Studio 2012\Projects\Temp\mobile-samples\MWC\MWC.Core\DL\SQLite.cs    2543    44  MWC.Core.WP7

I have the WP7.1 and 8.0 SDK. No modifications were used, the latest version of the master branch was retrieved from GitHub. The references are all valid.

**Comment by bradumbaugh** [comment]
Closing this issue since this sample has been deprecated.
