### ISSUE TITLE
Location Update Not Working

### ISSUE THREAD

**Issue by ronakshethia** [xamarin/mobile-samples#98]
The Location Update is not updating the location,
the  is not able to connect to the GPS

**Comment by bradumbaugh** [comment]
Hi @ronakshethia. Can you please provide a few more details? In particular, which sample are you looking at (assuming it's BackgroundLocationDemo?) and on which platform are you?

**Comment by ronakshethia** [comment]
@bradumbaugh I am testing this solution on my VIVO Phone who is running On Android 7.1 
and the method 
public void HandleLocationChanged(object sender, LocationChangedEventArgs e) {}
 
never gets triggers on when i change the device location.
![img_20180703_121340940_hdr](https://user-images.githubusercontent.com/35444818/42202885-b2f1d3be-7eba-11e8-9547-f296f2fd372d.jpg)
i am only getting the above output

**Comment by mgmclemore** [comment]
Hi @ronakshethia, I've verified that [BackgroundLocationDemo](https://developer.xamarin.com/samples/mobile/BackgroundLocationDemo/) runs correctly on Android 7.1 using Visual Studio 15.7.1 (testing on a Nexus 5X):

![android-screen-00](https://user-images.githubusercontent.com/8260693/42233642-fb4d0c32-7ea6-11e8-9a70-f3e8ebd694f8.png)

It's possible that you are running into a problem that is unique to your VIVO phone or your location. Unfortunately, our team can only answer feedback related to documentation, so your best for getting help is to visit the [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) forum. If you think this is a bug, please click **Report a problem** on that page. Thank you for your feedback!
