### ISSUE TITLE
[BackgroundLocationDemo: location.Android] - StartService not supported in Android 8+

### ISSUE THREAD

**Issue by DanJRWalsh** [xamarin/mobile-samples#99]
### Sample

Within [https://github.com/xamarin/mobile-samples/blob/master/BackgroundLocationDemo/location.Android/App.cs](https://github.com/xamarin/mobile-samples/blob/master/BackgroundLocationDemo/location.Android/App.cs)

> Android.App.Application.Context.StartService (new Intent (Android.App.Application.Context, typeof(LocationService)));

### Description

Context.StartService() was replaced with Context.StartForegroundService() as of Android 8.0.

The application needs to check the devices OS version and run the desired method to support both newer devices while being backward compatible.

Also, a check needs to be added in the LocationService.cs class as well for Android 8.0 and if so, call StartForeground() and pass an on-going notification along to it.

Refer to the foreground documents [here](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/foreground-services). The StartForegroundServiceComapt() method is a good example of this.

### Steps to Reproduce

Run the current code on an Android device running 8.0 or higher

### Expected Behavior

Location should continue to be logged in the background

### Actual Behavior

Location only logs in the foreground

### Information

- IDE and IDE version: Visual Studio 2017 v15.7.5
- Platform with the issue: 
  - Android: 8.0 or higher (SDK API Level 26+)
- Device or simulator/emulator: OnePlus 5T (Android 8.1)

**Comment by DanJRWalsh** [comment]
Solution:

Replace this in App.cs:
`Application.Context.StartService(new Intent(Application.Context, typeof(LocationService)));`

With
```
if (Build.VERSION.SdkInt >= BuildVersionCodes.O)
    Application.Context.StartForegroundService(new Intent(Application.Context, typeof(LocationService)));
else
    Application.Context.StartService(new Intent(Application.Context, typeof(LocationService)));`
```
and add this to OnStartCommand() in LocationService.cs
```
if (Build.VERSION.SdkInt >= BuildVersionCodes.O)
{
    Notification notification = new NotificationCompat.Builder(this, NOTIFICATION_CHANNEL_ID)
        .SetContentTitle(Resources.GetString(Resource.String.app_name))
        .SetContentText(Resources.GetString(Resource.String.notification_text))
        .SetSmallIcon(Resource.Drawable.notification_icon_background)
        .SetOngoing(true)
        .Build();

    NotificationManager notificationManager =
        GetSystemService(Context.NotificationService) as NotificationManager;

    NotificationChannel chan = new NotificationChannel(NOTIFICATION_CHANNEL_ID, "On-going                 Notification", NotificationImportance.Min);

    notificationManager.CreateNotificationChannel(chan);

    StartForeground(SERVICE_RUNNING_NOTIFICATION_ID, notification);
}
```

I've also added these two consts to the LocationService class which are referenced
```
private const int SERVICE_RUNNING_NOTIFICATION_ID = 123;
private const string NOTIFICATION_CHANNEL_ID = "com.company.app.channel";
```

**Comment by topgenorth** [comment]
Hi Dan,  thanks for reporting this and the code changes. We'll get to this as soon as we can. It  would really help us out and speed things up if you could put these changes into a PR and submit that (assign myself as the reviewer).   Thanks!

**Comment by DanJRWalsh** [comment]
@topgenorth Pull request #100 created. I'm unable to add a reviewer.

**Comment by DanJRWalsh** [comment]
PR #100 merged. Issue closed.
